apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-rc
spec:
  replicas: 2
  selector:
    app: helloworld
  template:
    metadata:
      name: helloworld-pod
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld-container
          image: wardviaene/k8s-demo
          ports:
            - containerPort: 3000
