apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 3
  revisionHistoryLimit: 10 # number of rollout history
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld-container
          image: wardviaene/k8s-demo
          ports:
            - name: nodejs-port
              containerPort: 3000
