apiVersion: v1
kind: Pod
metadata:
  name: helloworld-pod
  labels:
    app: helloworld
spec:
  containers:
    - name: helloworld-container
      image: wardviaene/k8s-demo
      ports:
        - name: nodejs-port
          containerPort: 3000
      volumeMounts:
        - name: cred-volume
          mountPath: /etc/creds # /etc/creds/db-secrets/username & /etc/creds/db-secrets/password
          readOnly: true

  volumes:
    - name: cred-volume
      secret:
        secretName: db-secrets
