---
apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  db-password: cGFzc3dvcmQ= # base64 of `password`

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - name: mysql-port
              containerPort: 3306

          resources:
            limits:
              ephemeral-storage: "1Gi"
              memory: 500Mi
              cpu: 200m
            requests:
              ephemeral-storage: "1Gi"
              memory: 500Mi
              cpu: 60m

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db-password

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:5-php7.4
          ports:
            - name: wordpress-port
              containerPort: 8080
          env:
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db-password
            - name: WORDPRESS_DB_HOST
              value: "mysql"

          resources:
            limits:
              memory: 500Mi
              cpu: 200m
            requests:
              memory: 500Mi
              cpu: 60m

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  ports:
    - port: 31001
      nodePort: 31001
      targetPort: wordpress-port
      protocol: TCP
  selector:
    app: wordpress
  type: NodePort
